In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print a

[1 2 3]


In [3]:
a.shape #array'in boyutu

(3,)

In [4]:
a[0], a[1], a[2]

(1, 2, 3)

In [5]:
b=np.array([[1,2,3],[4,5,6]])
print b

[[1 2 3]
 [4 5 6]]


In [6]:
b.shape

(2, 3)

In [7]:
b.itemsize #Elemanların byte boyutu

8

In [8]:
b.size #Toplam eleman sayısı

6

In [9]:
b.nbytes #Array'in toplam byte'ı

48

In [10]:
b.ndim #Array'in boyut sayısı

2

In [11]:
b[0,0], b[0,1], b[1,2]

(1, 2, 6)

In [12]:
zero=np.zeros((2,2))
print zero

[[ 0.  0.]
 [ 0.  0.]]


In [13]:
one=np.ones((1,2))
print one

[[ 1.  1.]]


In [14]:
full=np.full((2,2),7)
print full

[[7 7]
 [7 7]]


In [15]:
full.fill(5)
print full

[[5 5]
 [5 5]]


In [16]:
eye=np.eye(3)
print eye

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [17]:
rand=np.random.random((2,2))
print rand

[[ 0.2726983   0.78097375]
 [ 0.4329659   0.96579873]]


In [18]:
print b
bool_id=b>2
print bool_id

[[1 2 3]
 [4 5 6]]
[[False False  True]
 [ True  True  True]]


In [19]:
print b[b>2]

[3 4 5 6]


In [20]:
x=np.array([[1,5,8],[3,7,9]],float)
y=np.array([[2,4,3],[5,2,6]],float)
print x
print x.dtype #Değişken türü

[[ 1.  5.  8.]
 [ 3.  7.  9.]]
float64


In [21]:
x+y
#np.add(x,y) 

array([[  3.,   9.,  11.],
       [  8.,   9.,  15.]])

In [22]:
x-y
#np.subtract(x,y) 

array([[-1.,  1.,  5.],
       [-2.,  5.,  3.]])

In [23]:
x*y
#np.multiply(x,y)

array([[  2.,  20.,  24.],
       [ 15.,  14.,  54.]])

In [24]:
x/y
#np.divide(x,y)

array([[ 0.5       ,  1.25      ,  2.66666667],
       [ 0.6       ,  3.5       ,  1.5       ]])

In [25]:
np.sqrt(x) #x^0.5

array([[ 1.        ,  2.23606798,  2.82842712],
       [ 1.73205081,  2.64575131,  3.        ]])

In [26]:
np.square(x) #x^2

array([[  1.,  25.,  64.],
       [  9.,  49.,  81.]])

In [27]:
np.sum(x) #Elemanlar toplamı

33.0

In [28]:
x.min() #en küçük eleman

1.0

In [29]:
x.max() #En büyük eleman

9.0

In [30]:
v = np.array([9,10])
w = np.array([11, 12])
w.dot(v) #9*11+10*12

219

In [31]:
x.T #Traspose

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 8.,  9.]])

In [32]:
c=x.copy()
print c

[[ 1.  5.  8.]
 [ 3.  7.  9.]]


In [33]:
liste=c.tolist()
print liste

[[1.0, 5.0, 8.0], [3.0, 7.0, 9.0]]


In [34]:
np.tile(v,(4,3))

array([[ 9, 10,  9, 10,  9, 10],
       [ 9, 10,  9, 10,  9, 10],
       [ 9, 10,  9, 10,  9, 10],
       [ 9, 10,  9, 10,  9, 10]])

In [35]:
print x
xx=np.reshape(x,(3,-1)) #Array'i yeniden boyutlandırır.
xx

[[ 1.  5.  8.]
 [ 3.  7.  9.]]


array([[ 1.,  5.],
       [ 8.,  3.],
       [ 7.,  9.]])

In [36]:
xx.resize((2,3))
print xx

[[ 1.  5.  8.]
 [ 3.  7.  9.]]


In [37]:
np.arange(10,30,5) #10 dan 30'a kadar 5 artırır.

array([10, 15, 20, 25])

In [38]:
c=np.arange(24).reshape(2,3,4)
print c

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
np.linspace(0,2,9) #0-2 aralığını 9 a böler.

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [40]:
np.sin(x)

array([[ 0.84147098, -0.95892427,  0.98935825],
       [ 0.14112001,  0.6569866 ,  0.41211849]])

In [41]:
np.cos(x)

array([[ 0.54030231,  0.28366219, -0.14550003],
       [-0.9899925 ,  0.75390225, -0.91113026]])

In [42]:
np.tan(x)

array([[ 1.55740772, -3.38051501, -6.79971146],
       [-0.14254654,  0.87144798, -0.45231566]])

In [43]:
def f(e,r):
    return 10*e+r

fonk=np.fromfunction(f,(5,4),dtype=int)
print fonk

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [44]:
for i in fonk.flat:
    print i

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [45]:
fonk.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

# Referans Link
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

http://cs231n.github.io/python-numpy-tutorial/