# Contents
* [Numpy Arrays](#Numpy-Arrays)
* [Built-in Methods](#Built-in-Methods)
    * [Zeros](#Zeros)
    * [Ones](#Ones)
    * [Eye](#Eye)
    * [Full](#Full)
    * [Fill](#Fill)
    * [Linspace](#Linspace)
    * [Title](#Title)
* [Numpy Random](#Numpy-Random)
    * [Random](#Random)
    * [Rand](#Rand)
    * [Randn](#Randn)
    * [Randint](#Randint)
* [Arrange](#Arrange)
* [r_](#r_)
* [Fromfunction](#Fromfunction)
* [Numpy Operations](#Numpy-Operations)
    * [Boolen](#Boolen)
    * [Arithmetic Operation](#Arithmetic-Operation)
    * [Universal Array Functions](#Universal-Array-Functions)
    * [Trigonometric Function](#Trigonometric-Function)
* [Array Resize](#Array-Resize)
    * [Reshape](#Reshape)
    * [Resize](#Resize)
    * [Hsplit](#Hsplit)
    * [Newaxis](#Newaxis)
    * [Flatten](#Flatten)
* [Convert Array to List](#Convert-Array-to-List)
* [NumPy Indexing and Selection](#NumPy-Indexing-and-Selection)
    * [Indexing a 2D array (matrices)](#Indexing-a-2D-array-(matrices))
* [Copy The Array](#Copy-The-Array)
* [Combine The Arrays](#Combine-The-Arrays)
* [Referans Link](#Referans-Link)

In [1]:
import numpy as np #kütüphaneyi yükleyelim.

## Numpy Arrays

In [2]:
array=np.array([1,2,3])
print array

[1 2 3]


In [3]:
my_list = [1,2,3]
np.array(my_list)
print my_list

[1, 2, 3]


In [4]:
array.shape #array'in boyutu

(3,)

In [5]:
array[0], array[1], array[2]

(1, 2, 3)

In [6]:
matrix = np.array([[1,2,3],[4,5,6]])
print matrix

[[1 2 3]
 [4 5 6]]


In [7]:
matrix.shape 

(2, 3)

In [8]:
matrix.itemsize #Elemanların byte boyutu

8

In [9]:
matrix.size #Toplam eleman sayısı

6

In [10]:
matrix.nbytes #Array'in toplam byte'ı

48

In [11]:
matrix.ndim #Array'in boyut sayısı

2

In [12]:
matrix[0,0], matrix[0,1], matrix[1,2]

(1, 2, 6)

## Built-in Methods

### Zeros

In [13]:
zero=np.zeros((2,2))
print zero

[[0. 0.]
 [0. 0.]]


### Ones

In [14]:
one=np.ones((1,2))
print one

[[1. 1.]]


### Eye

In [15]:
eye=np.eye(3)
print eye

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Full

In [16]:
full=np.full((2,2),7)
print full

[[7 7]
 [7 7]]


### Fill

In [17]:
full.fill(5)
print full

[[5 5]
 [5 5]]


### Linspace

In [18]:
linspace = np.linspace(0,2,9) #0-2 aralığını 9 a böler.
print linspace

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### Title

In [19]:
v = np.array([[2, 5],[3,6]])

In [20]:
np.tile(v,(4,3)) #v'yi (x 4 satır) (x 3 sütun) olacak şekilde çolatır.

array([[2, 5, 2, 5, 2, 5],
       [3, 6, 3, 6, 3, 6],
       [2, 5, 2, 5, 2, 5],
       [3, 6, 3, 6, 3, 6],
       [2, 5, 2, 5, 2, 5],
       [3, 6, 3, 6, 3, 6],
       [2, 5, 2, 5, 2, 5],
       [3, 6, 3, 6, 3, 6]])

## Numpy Random

### Random

In [21]:
rand=np.random.random((2,2))
print rand

[[0.62472362 0.96677471]
 [0.6803138  0.87381323]]


### Rand

In [22]:
rand=np.random.rand(2,2)
print rand

[[0.38844304 0.40261422]
 [0.56528272 0.86369989]]


### Randn

In [23]:
randn=np.random.randn(2,2)
print randn

[[0.21731477 0.2776995 ]
 [1.57301392 0.13138566]]


### Randint

In [24]:
randint=np.random.randint(1,10)
print randint

3


In [25]:
randint=np.random.randint(1,100,10)
print randint

[83 80 86 34 60 14 44 33 45  7]


## Arrange

In [26]:
a = np.arange(0,10) #0 dan 10 a kadar sayı oluşturur.
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a = np.arange(10,30,5) #10 dan 30'a kadar 5 artırır.
a

array([10, 15, 20, 25])

## r_

In [28]:
print np.r_[1:8]
print np.r_[1:4,0,5,6]
print np.r_[1:10:2]

[1 2 3 4 5 6 7]
[1 2 3 0 5 6]
[1 3 5 7 9]


## Fromfunction

In [29]:
def f(e,r):
    return 10*e+r

fonk=np.fromfunction(f,(5,4),dtype=int)
print fonk

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


## Numpy Operations

In [30]:
x=np.array([[1,5,8],[3,7,9]],float)
y=np.array([[2,4,3],[5,2,6]],float)
print x
print x.dtype #Değişken türü

[[1. 5. 8.]
 [3. 7. 9.]]
float64


### Boolen

In [31]:
print x
bool_id=x>2
print bool_id

[[1. 5. 8.]
 [3. 7. 9.]]
[[False  True  True]
 [ True  True  True]]


In [32]:
print x[x>2]

[5. 8. 3. 7. 9.]


### Arithmetic Operation

In [33]:
x+y
#np.add(x,y) 

array([[ 3.,  9., 11.],
       [ 8.,  9., 15.]])

In [34]:
x-y
#np.subtract(x,y) 

array([[-1.,  1.,  5.],
       [-2.,  5.,  3.]])

In [35]:
x*y
#np.multiply(x,y)

array([[ 2., 20., 24.],
       [15., 14., 54.]])

In [36]:
x/y
#np.divide(x,y)

array([[0.5       , 1.25      , 2.66666667],
       [0.6       , 3.5       , 1.5       ]])

In [37]:
x**3 #x'in elemanlarının 3. kuvvetini alır.

array([[  1., 125., 512.],
       [ 27., 343., 729.]])

### Universal Array Functions

In [38]:
np.sqrt(x) #x^0.5

array([[1.        , 2.23606798, 2.82842712],
       [1.73205081, 2.64575131, 3.        ]])

In [39]:
np.square(x) #x^2

array([[ 1., 25., 64.],
       [ 9., 49., 81.]])

In [40]:
np.exp(x) #e^x

array([[2.71828183e+00, 1.48413159e+02, 2.98095799e+03],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

In [41]:
np.sum(x) #Elemanlar toplamı

33.0

In [42]:
x.min() #en küçük eleman

1.0

In [43]:
x.argmin() #en küçük elamanın indisi

0

In [44]:
x.max() #En büyük eleman

9.0

In [45]:
x.argmax() #En büyük elemanın indisi

5

In [46]:
#Eleman elemana çarpım
v = np.array([9,10])
w = np.array([11, 12])
w.dot(v) #9*11+10*12

219

In [47]:
x.T #Traspose

array([[1., 3.],
       [5., 7.],
       [8., 9.]])

### Trigonometric Function

In [48]:
np.sin(x)

array([[ 0.84147098, -0.95892427,  0.98935825],
       [ 0.14112001,  0.6569866 ,  0.41211849]])

In [49]:
np.sinh(x)

array([[1.17520119e+00, 7.42032106e+01, 1.49047883e+03],
       [1.00178749e+01, 5.48316123e+02, 4.05154190e+03]])

In [50]:
np.sinc(x)

array([[ 3.89817183e-17,  3.89817183e-17, -3.89817183e-17],
       [ 3.89817183e-17,  3.89817183e-17,  3.89817183e-17]])

In [51]:
np.cos(x)

array([[ 0.54030231,  0.28366219, -0.14550003],
       [-0.9899925 ,  0.75390225, -0.91113026]])

In [52]:
np.cosh(x)

array([[1.54308063e+00, 7.42099485e+01, 1.49047916e+03],
       [1.00676620e+01, 5.48317035e+02, 4.05154203e+03]])

In [53]:
np.tan(x)

array([[ 1.55740772, -3.38051501, -6.79971146],
       [-0.14254654,  0.87144798, -0.45231566]])

In [54]:
np.tanh(x)

array([[0.76159416, 0.9999092 , 0.99999977],
       [0.99505475, 0.99999834, 0.99999997]])

In [55]:
np.log(x)

array([[0.        , 1.60943791, 2.07944154],
       [1.09861229, 1.94591015, 2.19722458]])

## Array Resize

### Reshape

In [56]:
print x
xx=np.reshape(x,(3,-1)) #Array'i yeniden boyutlandırır.
xx

[[1. 5. 8.]
 [3. 7. 9.]]


array([[1., 5.],
       [8., 3.],
       [7., 9.]])

In [57]:
print x
x.reshape(1,6)

[[1. 5. 8.]
 [3. 7. 9.]]


array([[1., 5., 8., 3., 7., 9.]])

### Resize

In [58]:
xx.resize((2,3))
print xx

[[1. 5. 8.]
 [3. 7. 9.]]


In [59]:
c=np.arange(24).reshape(2,3,4)
print c

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Hsplit

In [60]:
a = np.floor(10*np.random.random((2,12)))
print a, "\n"

splite = np.hsplit(a,3)
print np.array(splite)

[[6. 4. 6. 8. 1. 4. 5. 2. 3. 2. 3. 9.]
 [5. 0. 6. 6. 3. 6. 0. 6. 8. 6. 8. 8.]] 

[[[6. 4. 6. 8.]
  [5. 0. 6. 6.]]

 [[1. 4. 5. 2.]
  [3. 6. 0. 6.]]

 [[3. 2. 3. 9.]
  [8. 6. 8. 8.]]]


### Newaxis

In [61]:
a = np.array([4.,2.])
print a
a[:,np.newaxis]

[4. 2.]


array([[4.],
       [2.]])

### Flatten

In [62]:
f=np.arange(24).reshape(2,3,4)
print f, "\n"
for i in f.flat:
    print i

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [63]:
print np.array(f.flat) #Matrisi vektör haline vetirdi.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [64]:
f.ravel() #Matrisi vektör haline vetirdi.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Convert Array to List 

In [65]:
print type(c)
liste=c.tolist()
print type(liste)

<type 'numpy.ndarray'>
<type 'list'>


## NumPy Indexing and Selection

In [66]:
arr = np.arange(0,11)
print arr

[ 0  1  2  3  4  5  6  7  8  9 10]


In [67]:
arr[8]

8

In [68]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
new_arr = arr[0:6]
print new_arr

[0 1 2 3 4 5]


In [70]:
arr[0:5]=100
print arr
print new_arr == arr[:6]
print new_arr

[100 100 100 100 100   5   6   7   8   9  10]
[ True  True  True  True  True  True]
[100 100 100 100 100   5]


In [71]:
print arr
print arr[::-1] #arrayi tersten yazdırır.

[100 100 100 100 100   5   6   7   8   9  10]
[ 10   9   8   7   6   5 100 100 100 100 100]


### Indexing a 2D array (matrices)

In [72]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

print arr_2d

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [73]:
arr_2d[1]

array([20, 25, 30])

In [74]:
arr_2d[1][0]

20

In [75]:
arr_2d[1,0]

20

In [76]:
arr_2d[:2,:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [77]:
arr_2d[2,:]

array([35, 40, 45])

## Copy The Array

In [78]:
x=np.array([[1,5,8],[3,7,9]])
print x
z=x #iki değişkende aynı adrese sahiptir.
x[0]=[20,30,40] #x'in bir kısmının değişmesi z yide değiştirir.
x[0]==z[0]

[[1 5 8]
 [3 7 9]]


array([ True,  True,  True])

In [79]:
x=np.array([[1,5,8],[3,7,9]])
print x

c = x.copy() #Birbirinden bağımsız olacak şekilde kopyalamak için copy metodu kullanılır.
x[0]=[20,30,40] #x'in bir kısmının değişmesi z yide değiştirir.

print x[0]==c[0]
print c

[[1 5 8]
 [3 7 9]]
[False False False]
[[1 5 8]
 [3 7 9]]


## Combine The Arrays

In [80]:
a = np.floor(10*np.random.random((2,2))) #floor sadece sayıların tam kısımlarını alır.
b = np.floor(10*np.random.random((2,2)))
print a
print b

[[4. 3.]
 [7. 4.]]
[[8. 4.]
 [0. 3.]]


In [81]:
np.vstack((a,b)) #vertical stack. Matrisleri dikey birleştirir.

array([[4., 3.],
       [7., 4.],
       [8., 4.],
       [0., 3.]])

In [82]:
np.hstack((a,b)) #horizontal stack. Matrisleri yatay birleştirir.

array([[4., 3., 8., 4.],
       [7., 4., 0., 3.]])

In [83]:
np.column_stack((a,b))

array([[4., 3., 8., 4.],
       [7., 4., 0., 3.]])

## Referans Link
### https://docs.scipy.org/doc/numpy/user/quickstart.html
### http://cs231n.github.io/python-numpy-tutorial/